const countryMap = 
[
    { countryName: 'Afghanistan', code: 'AF',visited:false},
    { countryName: 'Albania', code: 'AL',visited:false},
    { countryName: 'Algeria', code: 'DZ',visited:false},
    { countryName: 'American Samoa', code: 'AS',visited:false},
    { countryName: 'Andorra', code: 'AD',visited:false},
    { countryName: 'Angola', code: 'AO',visited:false},
    { countryName: 'Anguilla', code: 'AI',visited:false},
    { countryName: 'Antarctica', code: 'AQ',visited:false},
    { countryName: 'Antigua and Barbuda', code: 'AG',visited:false},
    { countryName: 'Argentina', code: 'AR',visited:false},
    { countryName: 'Armenia', code: 'AM',visited:false},
    { countryName: 'Aruba', code: 'AW',visited:false},
    { countryName: 'Australia', code: 'AU',visited:false},
    { countryName: 'Austria', code: 'AT',visited:false},
    { countryName: 'Azerbaijan', code: 'AZ',visited:false},
    { countryName: 'Bahamas', code: 'BS',visited:false},
    { countryName: 'Bahrain', code: 'BH',visited:false},
    { countryName: 'Bangladesh', code: 'BD',visited:false},
    { countryName: 'Barbados', code: 'BB',visited:false},
    { countryName: 'Belarus', code: 'BY',visited:false},
    { countryName: 'Belgium', code: 'BE',visited:true,fillColor:"#fae142"},
    { countryName: 'Belize', code: 'BZ',visited:false},
    { countryName: 'Benin', code: 'BJ',visited:false},
    { countryName: 'Bermuda', code: 'BM',visited:false},
    { countryName: 'Bhutan', code: 'BT',visited:false},
    { countryName: 'Bolivia, Plurinational State of', code: 'BO',visited:false},
    { countryName: 'Bonaire, Sint Eustatius and Saba', code: 'BQ',visited:false},
    { countryName: 'Bosnia and Herzegovina', code: 'BA',visited:false},
    { countryName: 'Botswana', code: 'BW',visited:false},
    { countryName: 'Bouvet Island', code: 'BV',visited:false},
    { countryName: 'Brazil', code: 'BR',visited:false},
    { countryName: 'British Indian Ocean Territory', code: 'IO',visited:false},
    { countryName: 'Brunei Darussalam', code: 'BN',visited:false},
    { countryName: 'Bulgaria', code: 'BG',visited:false},
    { countryName: 'Burkina Faso', code: 'BF',visited:false},
    { countryName: 'Burundi', code: 'BI',visited:false},
    { countryName: 'Cambodia', code: 'KH',visited:false},
    { countryName: 'Cameroon', code: 'CM',visited:false},
    { countryName: 'Canada', code: 'CA',visited:false},
    { countryName: 'Cape Verde', code: 'CV',visited:false},
    { countryName: 'Cayman Islands', code: 'KY',visited:false},
    { countryName: 'Central African Republic', code: 'CF',visited:false},
    { countryName: 'Chad', code: 'TD',visited:false},
    { countryName: 'Chile', code: 'CL',visited:false},
    { countryName: 'China', code: 'CN',visited:false},
    { countryName: 'Christmas Island', code: 'CX',visited:false},
    { countryName: 'Cocos (Keeling) Islands', code: 'CC',visited:false},
    { countryName: 'Colombia', code: 'CO',visited:false},
    { countryName: 'Comoros', code: 'KM',visited:false},
    { countryName: 'Congo', code: 'CG',visited:false},
    { countryName: 'Congo, the Democratic Republic of the', code: 'CD',visited:false},
    { countryName: 'Cook Islands', code: 'CK',visited:false},
    { countryName: 'Costa Rica', code: 'CR',visited:false},
    { countryName: 'Croatia', code: 'HR',visited:false},
    { countryName: 'Cuba', code: 'CU',visited:false},
    { countryName: 'Curaçao', code: 'CW',visited:false},
    { countryName: 'Cyprus', code: 'CY',visited:false},
    { countryName: 'Czech Republic', code: 'CZ',visited:true,fillColor:"#d7141a"},
    { countryName: "Côte d'Ivoire", code: 'CI',visited:false},
    { countryName: 'Denmark', code: 'DK',visited:false},
    { countryName: 'Djibouti', code: 'DJ',visited:false},
    { countryName: 'Dominica', code: 'DM',visited:false},
    { countryName: 'Dominican Republic', code: 'DO',visited:false},
    { countryName: 'Ecuador', code: 'EC',visited:false},
    { countryName: 'Egypt', code: 'EG',visited:true,fillColor:"#edb707"},
    { countryName: 'El Salvador', code: 'SV',visited:false},
    { countryName: 'Equatorial Guinea', code: 'GQ',visited:false},
    { countryName: 'Eritrea', code: 'ER',visited:false},
    { countryName: 'Estonia', code: 'EE',visited:false},
    { countryName: 'Ethiopia', code: 'ET',visited:false},
    { countryName: 'Falkland Islands (Malvinas)', code: 'FK',visited:false},
    { countryName: 'Faroe Islands', code: 'FO',visited:false},
    { countryName: 'Fiji', code: 'FJ',visited:false},
    { countryName: 'Finland', code: 'FI',visited:false},
    { countryName: 'France', code: 'FR',visited:true,fillColor:"#002395"},
    { countryName: 'French Guiana', code: 'GF',visited:false},
    { countryName: 'French Polynesia', code: 'PF',visited:false},
    { countryName: 'French Southern Territories', code: 'TF',visited:false},
    { countryName: 'Gabon', code: 'GA',visited:false},
    { countryName: 'Gambia', code: 'GM',visited:false},
    { countryName: 'Georgia', code: 'GE',visited:false},
    { countryName: 'Germany', code: 'DE',visited:true,fillColor:"#c10000"},
    { countryName: 'Ghana', code: 'GH',visited:false},
    { countryName: 'Gibraltar', code: 'GI',visited:false},
    { countryName: 'Greece', code: 'GR',visited:false},
    { countryName: 'Greenland', code: 'GL',visited:false},
    { countryName: 'Grenada', code: 'GD',visited:false},
    { countryName: 'Guadeloupe', code: 'GP',visited:false},
    { countryName: 'Guam', code: 'GU',visited:false},
    { countryName: 'Guatemala', code: 'GT',visited:false},
    { countryName: 'Guernsey', code: 'GG',visited:false},
    { countryName: 'Guinea', code: 'GN',visited:false},
    { countryName: 'Guinea-Bissau', code: 'GW',visited:false},
    { countryName: 'Guyana', code: 'GY',visited:false},
    { countryName: 'Haiti', code: 'HT',visited:false},
    { countryName: 'Heard Island and McDonald Islands', code: 'HM',visited:false},
    { countryName: 'Holy See (Vatican City State)', code: 'VA',visited:false},
    { countryName: 'Honduras', code: 'HN',visited:false},
    { countryName: 'Hong Kong', code: 'HK',visited:false},
    { countryName: 'Hungary', code: 'HU',visited:false},
    { countryName: 'Iceland', code: 'IS',visited:false},
    { countryName: 'India', code: 'IN',visited:true,fillColor:"#ff9933"},
    { countryName: 'Indonesia', code: 'ID',visited:false},
    { countryName: 'Iran, Islamic Republic of', code: 'IR',visited:false},
    { countryName: 'Iraq', code: 'IQ',visited:false},
    { countryName: 'Ireland', code: 'IE',visited:false},
    { countryName: 'Isle of Man', code: 'IM',visited:false},
    { countryName: 'Israel', code: 'IL',visited:false},
    { countryName: 'Italy', code: 'IT',visited:true,fillColor:"#009200"},
    { countryName: 'Jamaica', code: 'JM',visited:false},
    { countryName: 'Japan', code: 'JP',visited:false},
    { countryName: 'Jersey', code: 'JE',visited:false},
    { countryName: 'Jordan', code: 'JO',visited:false},
    { countryName: 'Kazakhstan', code: 'KZ',visited:false},
    { countryName: 'Kenya', code: 'KE',visited:false},
    { countryName: 'Kiribati', code: 'KI',visited:false},
    { countryName: "Korea, Democratic People's Republic of", code: 'KP',visited:false},
    { countryName: 'Korea, Republic of', code: 'KR',visited:false},
    { countryName: 'Kuwait', code: 'KW',visited:false},
    { countryName: 'Kyrgyzstan', code: 'KG',visited:false},
    { countryName: "Lao People's Democratic Republic", code: 'LA',visited:false},
    { countryName: 'Latvia', code: 'LV',visited:false},
    { countryName: 'Lebanon', code: 'LB',visited:false},
    { countryName: 'Lesotho', code: 'LS',visited:false},
    { countryName: 'Liberia', code: 'LR',visited:false},
    { countryName: 'Libya', code: 'LY',visited:false},
    { countryName: 'Liechtenstein', code: 'LI',visited:false},
    { countryName: 'Lithuania', code: 'LT',visited:false},
    { countryName: 'Luxembourg', code: 'LU',visited:false},
    { countryName: 'Macao', code: 'MO',visited:false},
    { countryName: 'Macedonia, the former Yugoslav Republic of', code: 'MK',visited:false},
    { countryName: 'Madagascar', code: 'MG',visited:false},
    { countryName: 'Malawi', code: 'MW',visited:false},
    { countryName: 'Malaysia', code: 'MY',visited:true,fillColor:"#ffcc00"},
    { countryName: 'Maldives', code: 'MV',visited:false},
    { countryName: 'Mali', code: 'ML',visited:false},
    { countryName: 'Malta', code: 'MT',visited:false},
    { countryName: 'Marshall Islands', code: 'MH',visited:false},
    { countryName: 'Martinique', code: 'MQ',visited:false},
    { countryName: 'Mauritania', code: 'MR',visited:false},
    { countryName: 'Mauritius', code: 'MU',visited:false},
    { countryName: 'Mayotte', code: 'YT',visited:false},
    { countryName: 'Mexico', code: 'MX',visited:false},
    { countryName: 'Micronesia, Federated States of', code: 'FM',visited:false},
    { countryName: 'Moldova, Republic of', code: 'MD',visited:false},
    { countryName: 'Monaco', code: 'MC',visited:false},
    { countryName: 'Mongolia', code: 'MN',visited:false},
    { countryName: 'Montenegro', code: 'ME',visited:false},
    { countryName: 'Montserrat', code: 'MS',visited:false},
    { countryName: 'Morocco', code: 'MA',visited:false},
    { countryName: 'Mozambique', code: 'MZ',visited:false},
    { countryName: 'Myanmar', code: 'MM',visited:false},
    { countryName: 'Namibia', code: 'NA',visited:false},
    { countryName: 'Nauru', code: 'NR',visited:false},
    { countryName: 'Nepal', code: 'NP',visited:false},
    { countryName: 'Netherlands', code: 'NL',visited:true,fillColor:"#21468b"},
    { countryName: 'New Caledonia', code: 'NC',visited:false},
    { countryName: 'New Zealand', code: 'NZ',visited:false},
    { countryName: 'Nicaragua', code: 'NI',visited:false},
    { countryName: 'Niger', code: 'NE',visited:false},
    { countryName: 'Nigeria', code: 'NG',visited:false},
    { countryName: 'Niue', code: 'NU',visited:false},
    { countryName: 'Norfolk Island', code: 'NF',visited:false},
    { countryName: 'Northern Mariana Islands', code: 'MP',visited:false},
    { countryName: 'Norway', code: 'NO',visited:false},
    { countryName: 'Oman', code: 'OM',visited:false},
    { countryName: 'Pakistan', code: 'PK',visited:false},
    { countryName: 'Palau', code: 'PW',visited:false},
    { countryName: 'Palestine, State of', code: 'PS',visited:false},
    { countryName: 'Panama', code: 'PA',visited:false},
    { countryName: 'Papua New Guinea', code: 'PG',visited:false},
    { countryName: 'Paraguay', code: 'PY',visited:false},
    { countryName: 'Peru', code: 'PE',visited:false},
    { countryName: 'Philippines', code: 'PH',visited:false},
    { countryName: 'Pitcairn', code: 'PN',visited:false},
    { countryName: 'Poland', code: 'PL',visited:false},
    { countryName: 'Portugal', code: 'PT',visited:false},
    { countryName: 'Puerto Rico', code: 'PR',visited:false},
    { countryName: 'Qatar', code: 'QA',visited:false},
    { countryName: 'Romania', code: 'RO',visited:false},
    { countryName: 'Russian Federation', code: 'RU',visited:false},
    { countryName: 'Rwanda', code: 'RW',visited:false},
    { countryName: 'Réunion', code: 'RE',visited:false},
    { countryName: 'Saint Barthélemy', code: 'BL',visited:false},
    { countryName: 'Saint Helena, Ascension and Tristan da Cunha', code: 'SH',visited:false},
    { countryName: 'Saint Kitts and Nevis', code: 'KN',visited:false},
    { countryName: 'Saint Lucia', code: 'LC',visited:false},
    { countryName: 'Saint Martin (French part)', code: 'MF',visited:false},
    { countryName: 'Saint Pierre and Miquelon', code: 'PM',visited:false},
    { countryName: 'Saint Vincent and the Grenadines', code: 'VC',visited:false},
    { countryName: 'Samoa', code: 'WS',visited:false},
    { countryName: 'San Marino', code: 'SM',visited:false},
    { countryName: 'Sao Tome and Principe', code: 'ST',visited:false},
    { countryName: 'Saudi Arabia', code: 'SA',visited:false},
    { countryName: 'Senegal', code: 'SN',visited:false},
    { countryName: 'Serbia', code: 'RS',visited:false},
    { countryName: 'Seychelles', code: 'SC',visited:false},
    { countryName: 'Sierra Leone', code: 'SL',visited:false},
    { countryName: 'Singapore', code: 'SG',visited:false},
    { countryName: 'Sint Maarten (Dutch part)', code: 'SX',visited:false},
    { countryName: 'Slovakia', code: 'SK',visited:false},
    { countryName: 'Slovenia', code: 'SI',visited:false},
    { countryName: 'Solomon Islands', code: 'SB',visited:false},
    { countryName: 'Somalia', code: 'SO',visited:false},
    { countryName: 'South Africa', code: 'ZA',visited:false},
    { countryName: 'South Georgia and the South Sandwich Islands', code: 'GS',visited:false},
    { countryName: 'South Sudan', code: 'SS',visited:false},
    { countryName: 'Spain', code: 'ES',visited:true,fillColor:"#8a0b1e"},
    { countryName: 'Sri Lanka', code: 'LK',visited:false},
    { countryName: 'Sudan', code: 'SD',visited:false},
    { countryName: 'Suriname', code: 'SR',visited:false},
    { countryName: 'Svalbard and Jan Mayen', code: 'SJ',visited:false},
    { countryName: 'Swaziland', code: 'SZ',visited:false},
    { countryName: 'Sweden', code: 'SE',visited:true,fillColor:'#006aa7'},
    { countryName: 'Switzerland', code: 'CH',visited:true,fillColor:'#ff0000'},
    { countryName: 'Syrian Arab Republic', code: 'SY',visited:false},
    { countryName: 'Taiwan, Province of China', code: 'TW',visited:false},
    { countryName: 'Tajikistan', code: 'TJ',visited:false},
    { countryName: 'Tanzania, United Republic of', code: 'TZ',visited:false},
    { countryName: 'Thailand', code: 'TH',visited:true,fillColor:'#120c5a'},
    { countryName: 'Timor-Leste', code: 'TL',visited:false},
    { countryName: 'Togo', code: 'TG',visited:false},
    { countryName: 'Tokelau', code: 'TK',visited:false},
    { countryName: 'Tonga', code: 'TO',visited:false},
    { countryName: 'Trinidad and Tobago', code: 'TT',visited:false},
    { countryName: 'Tunisia', code: 'TN',visited:false},
    { countryName: 'Turkey', code: 'TR',visited:false},
    { countryName: 'Turkmenistan', code: 'TM',visited:false},
    { countryName: 'Turks and Caicos Islands', code: 'TC',visited:false},
    { countryName: 'Tuvalu', code: 'TV',visited:false},
    { countryName: 'Uganda', code: 'UG',visited:false},
    { countryName: 'Ukraine', code: 'UA',visited:false},
    { countryName: 'United Arab Emirates', code: 'AE',visited:false},
    { countryName: 'United Kingdom', code: 'GB',visited:false},
    { countryName: 'United States', code: 'US',visited:false},
    { countryName: 'United States Minor Outlying Islands', code: 'UM',visited:false},
    { countryName: 'Uruguay', code: 'UY',visited:false},
    { countryName: 'Uzbekistan', code: 'UZ',visited:false},
    { countryName: 'Vanuatu', code: 'VU',visited:false},
    { countryName: 'Venezuela, Bolivarian Republic of', code: 'VE',visited:false},
    { countryName: 'Viet Nam', code: 'VN',visited:false},
    { countryName: 'Virgin Islands, British', code: 'VG',visited:false},
    { countryName: 'Virgin Islands, U.S.', code: 'VI',visited:false},
    { countryName: 'Wallis and Futuna', code: 'WF',visited:false},
    { countryName: 'Western Sahara', code: 'EH',visited:false},
    { countryName: 'Yemen', code: 'YE',visited:false},
    { countryName: 'Zambia', code: 'ZM',visited:false},
    { countryName: 'Zimbabwe', code: 'ZW',visited:false},
    { countryName: 'Åland Islands', code: 'AX' }
]

export default countryMap;